### ISSUE TITLE
End of railway?

### ISSUE THREAD

**Issue by Maniktherana** [anandrmedia/heroku-free-alternatives#32]
Looks like railway is removing their [free tier](https://blog.railway.app/p/introducing-trial-hobby-pro-plans)

There is a trial worth $5 credits [according to their docs](https://docs.railway.app/reference/pricing) but not sure how long that will last

**Comment by ftr9** [comment]
The Starter plan will be discontinued on August 1, 2023. Upgrade to the Hobby plan to continue using Railway. railway should be removed from the list

**Comment by anandrmedia** [comment]
Removed
